ui:
  base_url: "https://wmxrwq14uc.execute-api.us-east-1.amazonaws.com/Prod/Account/Login"

api:
  base_url: "https://wmxrwq14uc.execute-api.us-east-1.amazonaws.com/Prod/api/"

browser: chrome
implicit_wait: 5
